<?php get_header(); ?>
<main class="site-main home-page">
    <section class="home-hero"><div class="shell home-hero-grid"><div class="home-hero-copy"><p class="eyebrow">Wspólny głos polskiego drobiarstwa</p><h1>Partner branży -<br><em>Głos sektora.</em></h1><p>Reprezentujemy producentów, hodowców i przetwórców. Wspieramy zrównoważoną produkcję, rozwój eksportu oraz rzetelną wiedzę o polskim drobiu.</p><div class="hero-actions"><a class="button button-primary" href="<?php echo esc_url(home_url('/o-izbie/')); ?>">Poznaj KRD-IG <span class="arrow">↗</span></a><a class="button button-quiet" href="<?php echo esc_url(home_url('/aktualnosci/')); ?>">Najnowsze informacje</a></div></div></div></section>
    <section class="home-stats"><div class="site-width stats-grid"><div><p class="eyebrow eyebrow-light">Rynek</p><h2>Polski drób ma światową skalę</h2></div><div><strong>№ 1</strong><p>producent mięsa drobiowego w Unii Europejskiej</p></div><div><strong>2,4 mln ton*</strong><p>eksportu mięsa i przetworów drobiowych</p></div><div><strong>6,2 mld €*</strong><p>wartości eksportu drobiu i jego przetworów</p></div></div></section>
    <section class="pillars-section"><div class="shell"><div class="section-intro pillars-intro"><p class="eyebrow">Cztery filary rozwoju</p><h2><span>CZTERY FILARY ROZWOJU</span><span>POLSKIEGO DROBIARSTWA</span></h2></div><div class="pillars-grid"><article class="pillar-card pillar-card--shield"><span class="pillar-number">I</span><h3>Bezpieczeństwo białkowe</h3><p>Kluczowe zagadnienie dla polskiego drobiarstwa i jeden z naszych najważniejszych priorytetów.</p><a href="<?php echo esc_url(home_url('/bezpieczenstwo-bialkowe/')); ?>">Zobacz więcej ↗</a></article><article class="pillar-card pillar-card--leaf"><span class="pillar-number">II</span><h3>Zrównoważony rozwój</h3><p>Standardy kontroli produkcji, dobrostanu zwierząt i ochrony środowiska.</p><a href="<?php echo esc_url(home_url('/zrownowazony-rozwoj/')); ?>">Zobacz więcej ↗</a></article><article class="pillar-card pillar-card--megaphone"><span class="pillar-number">III</span><h3>Wizerunek i promocja</h3><p>Wspólna strategia promowania drobiu jako bezpiecznej i wartościowej żywności.</p><a href="<?php echo esc_url(home_url('/promocja-drobiu/')); ?>">Zobacz więcej ↗</a></article><article class="pillar-card pillar-card--globe"><span class="pillar-number">IV</span><h3>Globalizacja rynku</h3><p>Nowe rynki zbytu i europejskie standardy produkcji promowane na świecie.</p><a href="<?php echo esc_url(home_url('/globalizacja-rynku/')); ?>">Zobacz więcej ↗</a></article></div></div></section>
    <section class="pathways"><div class="shell"><div class="section-intro intro-row"><div><p class="eyebrow">Najważniejsze obszary</p><h2>Wszystkie informacje na wyciągnięcie ręki</h2></div><p>Czytelne ścieżki do danych, dokumentów i wiedzy.</p></div><div class="pathway-grid">
        <?php $areas = array(array('rynek','Rynek i handel','Dane, raporty, eksport, Unia Europejska i rynki eksportowe.'),array('hodowla','Hodowla i ocena','Księgi, rejestry, metodyka, wstawienia i certyfikacja.'),array('zrownowazony-rozwoj','Jakość i rozwój','QAFP, bezpieczeństwo produkcji, dobrostan i środowisko.'),array('dezinformacja','Rzetelnie o drobiu','Fakty, materiały edukacyjne i przeciwdziałanie manipulacji.')); foreach ($areas as $area) : ?><a class="pathway-card" href="<?php echo esc_url(home_url('/'.$area[0].'/')); ?>"><span>→</span><h3><?php echo esc_html($area[1]); ?></h3><p><?php echo esc_html($area[2]); ?></p></a><?php endforeach; ?>
    </div></div></section>
    <section class="home-section latest-section"><div class="site-width"><div class="section-heading"><div><p class="eyebrow">Aktualności</p><h2>W centrum wydarzeń</h2></div><a class="button button-outline" href="<?php echo esc_url(get_post_type_archive_link('aktualnosc')); ?>">Pełne archiwum ↗</a></div><div class="latest-grid">
        <?php $latest = new WP_Query(array('post_type'=>'aktualnosc','posts_per_page'=>4,'post_status'=>'publish')); if ($latest->have_posts()) : while ($latest->have_posts()) : $latest->the_post(); ?><article class="latest-card"><?php if (has_post_thumbnail()) { the_post_thumbnail('medium_large'); } ?><div><p class="latest-meta"><?php echo esc_html(get_the_date()); ?></p><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html(wp_trim_words(get_the_excerpt(), 24)); ?></p><a href="<?php the_permalink(); ?>">Czytaj dalej ↗</a></div></article><?php endwhile; wp_reset_postdata(); else : ?><p>Dodaj aktualności w panelu WordPressa.</p><?php endif; ?>
    </div></div></section>
    <section class="membership-cta"><div class="site-width"><p class="eyebrow eyebrow-light">Członkostwo</p><h2>Razem mamy większy wpływ</h2><p>Dołącz do przedsiębiorców, którzy wspólnie kształtują przyszłość polskiego sektora drobiarskiego.</p><a class="button button-white" href="<?php echo esc_url(home_url('/czlonkostwo/')); ?>">Poznaj korzyści ↗</a></div></section>
</main><?php get_footer(); ?>